FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Vite default port
EXPOSE 3001

# We use --host to allow the container to expose the service to your browser
CMD ["npm", "run", "dev", "--", "--host"]